Entry.create!(name: "Matz")
Entry.create!(name: "DHH")
Entry.create!(name: "Jose Valim")
Entry.create!(name: "Avdi Grimm")
Entry.create!(name: "Steve Klabnik")
Entry.create!(name: "Aaron Patterson")

Item.create!(name: "Hard Shell", price: 2.00)
Item.create!(name: "Soft Shell", price: 2.25)
Item.create!(name: "Black Beans", price: 1.50)
Item.create!(name: "Lettuce", price: 2.00)
Item.create!(name: "Ground Meat", price: 3.60)
Item.create!(name: "Lean Ground Meat", price: 4.25)
Item.create!(name: "Grilled Chicken", price: 5.15)
Item.create!(name: "Cheddar Cheese", price: 2.00)
Item.create!(name: "Special Salsa", price: 6.00)
  